on:
  push:
    branches:
      - dev

jobs:
  publish:
    name: Publish Dev Build
    runs-on: ubuntu-latest
    if: |
      !contains(github.event.head_commit.message, 'skip ci') ||
      github.repository !== 'pikokr/typescript-sample-module'
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16.6
      - run: yarn
      - run: COMMIT_ID=$(git rev-parse --short HEAD) node publish-version.js
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          tag: dev
